image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  script: |-
    docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" "$DOCKER_REGISTRY"
    docker build -t "$DOCKER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME" .
    docker push "$DOCKER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME"

    TAG_ALIAS=$(echo $CI_COMMIT_REF_NAME | sed 's/-.*$//')
    if [ "$CI_COMMIT_REF_NAME" != "$TAG_ALIAS" ]; then
      docker tag "$DOCKER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME" "$DOCKER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$TAG_ALIAS"
      docker push "$DOCKER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$TAG_ALIAS"
    fi
  only:
    - tags

deploy:chart:
  stage: deploy
  script:
    - curl -s -X POST -F token=$GITLAB_TOKEN -F ref=master https://gitlab.funix.nl/api/v4/projects/149/trigger/pipeline
  only:
    refs:
      - master
