{{- if .Values.rbac.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "node-health-agent.rbacName" . }}
  labels:
    {{- include "node-health-agent.labels" . | nindent 4 }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "node-health-agent.rbacName" . }}
  labels:
    {{- include "node-health-agent.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "node-health-agent.rbacName" . }}
  labels:
    {{- include "node-health-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "node-health-agent.rbacName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "node-health-agent.rbacName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
